"""
FinAx API
=========
Serves the classified news feed generated by FinAx engine.
FinAx classifies news from RSS feeds using Groq AI.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Query

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/finax", tags=["FinAx"])

PROJECT_ROOT = Path(__file__).parent.parent.parent
FINAX_OUTPUT = PROJECT_ROOT.parent / "apps" / "FinAx" / "output" / "finax_feed.json"


@router.get("/feed")
async def get_news_feed(
    limit: int = Query(default=50, ge=1, le=500),
    category: Optional[str] = None,
):
    """
    Get classified news articles from FinAx.
    Optional filter by category.
    """
    if not FINAX_OUTPUT.exists():
        return {"articles": [], "status": "no_data", "path": str(FINAX_OUTPUT)}

    try:
        articles = json.loads(FINAX_OUTPUT.read_text(encoding="utf-8"))
        if not isinstance(articles, list):
            return {"articles": [], "status": "invalid_format"}

        if category:
            articles = [a for a in articles if a.get("category", "").lower() == category.lower()]

        articles = sorted(articles, key=lambda x: x.get("published", ""), reverse=True)[:limit]

        return {
            "articles": articles,
            "total": len(articles),
            "status": "ok",
        }
    except Exception as e:
        logger.warning(f"FinAx feed read failed: {e}")
        return {"articles": [], "status": "error", "error": str(e)}


@router.get("/health")
async def finax_health():
    """FinAx data availability."""
    exists = FINAX_OUTPUT.exists()
    count = 0
    latest = None
    if exists:
        try:
            data = json.loads(FINAX_OUTPUT.read_text(encoding="utf-8"))
            if isinstance(data, list):
                count = len(data)
                if data:
                    latest = data[0].get("published") or data[0].get("fetched_at")
        except Exception:
            pass

    return {
        "status": "available" if exists and count > 0 else "unavailable",
        "article_count": count,
        "latest_article": latest,
    }
